### ISSUE TITLE
No module named 'pycmsg'

### ISSUE THREAD

**Issue by MartianColonist** [rhdtownsend/msg#22]
After installing MSG-1.3 on Ubuntu 20.04 in a fresh conda environment, I'm hitting the following error upon importing pymsg:

Traceback (most recent call last):
    import pymsg as pymsg
  File "/home/....../anaconda3/envs/....../lib/python3.11/site-packages/pymsg/__init__.py", line 29, in <module>
    import pycmsg as pyc
ModuleNotFoundError: No module named 'pycmsg'

Is there any additional step, beyond those in the installation instructions in the MSG documentation, to install the pycmsg submodule?

**Comment by MartianColonist** [comment]
It looks like to solve this problem the user needs 'cython' to be installed in their conda environment before compiling MSG ('make -j -C $MSG_DIR').

Can you add a note on the installation page under 'Building MSG' noting that cython is a prerequisite for pymsg?

**Comment by rhdtownsend** [comment]
Nice catch. I though I had set things up so that when Cython isn't available, the generated C source code (src/cython/pycmsg.c) gets used instead. However, the vpath definitions necessary to make this work are missing from build/Make.inc.

As a workaround, if you don't want to install Cython, just run the following before you run make:

`cp $MSG_DIR/src/cython/pycmsg.c $MSG_DIR/build/`

**Comment by maxkroft** [comment]
I'm having this issue as well. I am on version 2.2, running wsl on ubuntu. I am getting the exact same error as the original post:

>>> import pymsg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kroft/miniconda3/envs/msg/lib/python3.12/site-packages/pymsg/__init__.py", line 32, in <module>
    import pycmsg as pyc
ModuleNotFoundError: No module named 'pycmsg'

However, I did have cython installed when running make -C MSG_DIR (it crashed before I pointed to my python). Everything compiled, and running the test command everything passed. I then pip installed pymsg.

I've also double checked that the path that is added to sys.path on the line before is pointing to the correct place (MSG_DIR/lib), however there is no pycmsg file in the lib folder.

**Comment by rhdtownsend** [comment]
Can you post the output of the make command? I'd like to see the error message that's causing the pycmsg module not to build.

**Comment by maxkroft** [comment]
When I run make -C $MSG_DIR on a clean directory, I get to this point:

make: Entering directory '/home/kroft/msg'
MAKEDEP libforum
FC arg_parser_m
FC cinter_m
FC const_m
FC forum_m
FC hdf5io_m
FC kinds_m
FC memory_m
FC order_m
FC string_m
FC system_m
FC version_m
AR-LIB libforum.a
LD-LIB libforum.so
CP libforum.a /home/kroft/msg/lib/libforum.a
CP libforum.so /home/kroft/msg/lib/libforum.so
CP forum.pc /home/kroft/msg/lib/pkgconfig/forum.pc
CP forum_m.mod /home/kroft/msg/include/forum_m.mod
CP forum.inc /home/kroft/msg/include/forum.inc
Make.inc:31: *** No cython found, consider installing with pip, conda, etc.  Stop.
make: *** [Makefile:71: build] Error 2
make: Leaving directory '/home/kroft/msg'

To get it to run, I modified the command like this so that it is pointed to a python installation with cython: make -C $MSG_DIR PYTHON=/home/kroft/miniconda3/envs/msg/bin/python

Then it runs all the way through with no errors, runs all these cp commands at the end:

CP utest_file /home/kroft/msg/bin/utest_file
CP utest_fit /home/kroft/msg/bin/utest_fit
CP utest_math /home/kroft/msg/bin/utest_math
CP utest_cubint /home/kroft/msg/bin/utest_cubint
CP utest_ninterp /home/kroft/msg/bin/utest_ninterp
CP utest_axis /home/kroft/msg/bin/utest_axis
CP utest_indexer /home/kroft/msg/bin/utest_indexer
CP utest_vgrid /home/kroft/msg/bin/utest_vgrid
CP utest_specgrid /home/kroft/msg/bin/utest_specgrid
CP utest_photgrid /home/kroft/msg/bin/utest_photgrid
CP utest_lin_range /home/kroft/msg/bin/utest_lin_range
CP utest_log_range /home/kroft/msg/bin/utest_log_range
CP utest_tab_range /home/kroft/msg/bin/utest_tab_range
CP utest_comp_range /home/kroft/msg/bin/utest_comp_range
CP stress_specgrid /home/kroft/msg/bin/stress_specgrid
CP stress_photgrid /home/kroft/msg/bin/stress_photgrid
CP time_vgrid /home/kroft/msg/bin/time_vgrid
CP time_specgrid /home/kroft/msg/bin/time_specgrid
CP ascii_to_specint /home/kroft/msg/bin/ascii_to_specint
CP synspec_to_specint /home/kroft/msg/bin/synspec_to_specint
CP ferre_to_specint /home/kroft/msg/bin/ferre_to_specint
CP c3k_to_specint /home/kroft/msg/bin/c3k_to_specint
CP newera_to_specint /home/kroft/msg/bin/newera_to_specint
CP rebin_specint /home/kroft/msg/bin/rebin_specint
CP make_bb_photgrid /home/kroft/msg/bin/make_bb_photgrid
CP specgrid_to_photgrid /home/kroft/msg/bin/specgrid_to_photgrid
CP specint_to_specgrid /home/kroft/msg/bin/specint_to_specgrid
CP make_passband /home/kroft/msg/bin/make_passband
CP make_photon_passband /home/kroft/msg/bin/make_photon_passband
CP inspect_grid /home/kroft/msg/bin/inspect_grid
CP subset_specgrid /home/kroft/msg/bin/subset_specgrid
CP subset_photgrid /home/kroft/msg/bin/subset_photgrid
CP libmsg.a /home/kroft/msg/lib/libmsg.a
CP libfmsg.a /home/kroft/msg/lib/libfmsg.a
CP libcmsg.a /home/kroft/msg/lib/libcmsg.a
CP libmsg.so /home/kroft/msg/lib/libmsg.so
CP libfmsg.so /home/kroft/msg/lib/libfmsg.so
CP libcmsg.so /home/kroft/msg/lib/libcmsg.so
CP msg.pc /home/kroft/msg/lib/pkgconfig/msg.pc
CP fmsg.pc /home/kroft/msg/lib/pkgconfig/fmsg.pc
CP cmsg.pc /home/kroft/msg/lib/pkgconfig/cmsg.pc
CP msg_m.mod /home/kroft/msg/include/msg_m.mod
CP fmsg_m.mod /home/kroft/msg/include/fmsg_m.mod
CP cmsg_m.mod /home/kroft/msg/include/cmsg_m.mod
CP cmsg.h /home/kroft/msg/include/cmsg.h

Finally, make -C $MSG_DIR test passes 146 with 0 failures

**Comment by rhdtownsend** [comment]
It seems your setting the PYTHON variable when you run make is having an unintended side effect. If this variable is not set to 'yes', then the build system won't compile the Python library. That's why pycmsg isn't getting built.

As a workaround, can you try *not* setting this variable, and instead activating the appropriate Python venv using 'source home/kroft/miniconda3/envs/msg/bin/activate'

**Comment by maxkroft** [comment]
Ok after setting the python env I now get a new error at CYTHON pycmsg

CYTHON pycmsg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import numpy; print(numpy.get_include())
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'numpy'
CC pycmsg
pycmsg.c:1254:10: fatal error: numpy/arrayobject.h: No such file or directory
 1254 | #include "numpy/arrayobject.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Make.inc:213: pycmsg.o] Error 1
rm pycmsg.c
make: *** [Makefile:71: build] Error 2

**Comment by maxkroft** [comment]
I have fixed it I believe. I had an issue where my default path was pointing to linuxbrew for some reason. I now have the pycmsg.cpython file in my msg/lib

**Comment by rhdtownsend** [comment]
Your numpy error is because numpy isn't installed. I'm going to add a check so that the compilation failure is less cryptic (same for cython). Glad things are working OK now!

**Comment by MartianColonist** [comment]
Hi Richard,

I'm seeing a related error in a fresh install of pymsg 2.2. I have cython in my conda environment and all the tests pass. But when going to run pymsg, I encounter the following error:

>   File "/sharedscratch/rm440/code/POSEIDON/POSEIDON/stellar.py", line 148, in open_pymsg_grid
>     specgrid = pymsg.SpecGrid(specgrid_file_name)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/software/conda/rm440/conda/envs/POSEIDON/lib/python3.12/site-packages/pymsg/__init__.py", line 63, in __init__
>     self._specgrid = pyc._load_specgrid(file_name)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pycmsg.pyx", line 34, in pycmsg._load_specgrid
>   File "pycmsg.pyx", line 479, in pycmsg._handle_error
> FileNotFoundError: file not found

I have tried copying pycmsg.pyx into the build folder, as you suggested above, but the same error occurs.

**Comment by rhdtownsend** [comment]
This isn't a build issue -- it looks like the file you're trying to load (stored in the specgrid_file_name variable) isn't being found. Can you check that the file is there?

**Comment by MartianColonist** [comment]
Aha, yes, the error was that I didn't have the sg-Goettingen-HiRes.h5 file - all good now!

**Comment by rhdtownsend** [comment]
I've just pushed a new release, 24c7e1d (v2.2.1), that should finally resolve these issues by warning the user when the required Python modules (numpy, cython) are not installed. Closing as resolved.
